# Generated by Django 3.0.6 on 2020-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('lang', models.CharField(default='uk', max_length=10)),
            ],
        ),
    ]
