# Generated by Django 3.0.6 on 2020-06-06 09:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200604_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
