# Generated by Django 3.0.6 on 2020-06-08 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200608_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
