# Generated by Django 3.0.6 on 2020-06-09 15:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200608_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'simple_text'), (1, 'booking')]),
        ),
    ]
