# Generated by Django 3.0.7 on 2020-06-16 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200609_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('notification', models.DateTimeField()),
                ('date_from', models.DateField(auto_now=True, null=True)),
                ('date_to', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '_category', 'verbose_name_plural': '_categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '_order', 'verbose_name_plural': '_orders'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '_company', 'verbose_name_plural': '_companies'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '_grade', 'verbose_name_plural': '_grades'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '_order', 'verbose_name_plural': '_orders'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '_profile', 'verbose_name_plural': '_profiles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '_service', 'verbose_name_plural': '_services'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'telegram_user', 'verbose_name_plural': 'telegram_users'},
        ),
        migrations.AlterModelOptions(
            name='timework',
            options={'verbose_name': '_time_work', 'verbose_name_plural': '_time_works'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.Category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='news',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='backend.Company'),
        ),
    ]
