# Generated by Django 3.0.7 on 2020-06-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200616_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '_news', 'verbose_name_plural': '_more_news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WatchCompanyTelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='backend.Company')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='backend.TelegramUser')),
            ],
            options={
                'unique_together': {('telegram_user', 'company')},
            },
        ),
    ]
