# Generated by Django 3.0.6 on 2020-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200617_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
